name: Mise a jour automatique

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Récupérer les fichiers
        uses: actions/checkout@v4

      - name: 🚀 Envoyer chez Infomaniak
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          port: 21
          secure: false
